
    menuItem
        -label "Maint" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem2;

        menuItem
            -label "FreezeTrans" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "FreezeTransformations;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "//halonblade/hblade/InProd/AP3S/assets/SCRIPTS/icons/FreezeTransforms.bmp" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "CenterPivot" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CenterPivot;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "//halonblade/hblade/InProd/AP3S/assets/SCRIPTS/icons/centerPivot.bmp" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "DeleteHistory" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DeleteHistory;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "//halonblade/hblade/InProd/AP3S/assets/SCRIPTS/icons/DeleteHistory.bmp" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem17;

        menuItem
            -label "Windows" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "S" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem20;

            menuItem
                -label "MarkingMenus" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "MarkingMenuPreferencesWindow;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "ScriptEd" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ScriptEditor;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Prefs" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PreferencesWindow;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "UV Ed" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "TextureViewWindow;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "HyperShade" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "HypershadeWindow;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "PluginManager" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PluginManager;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "Namespace Ed" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "NamespaceEditor;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem8;

            menuItem
                -label "Show All UI Elements" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowUIElements" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconDisplay.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

        setParent -m ..;

        menuItem
            -label "Files" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem21;

            menuItem
                -label "Save Preferences" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SavePreferences" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconFile.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Optimize Scene Size" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OptimizeScene" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconFile.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Reload Current Scene No Save" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/UTIL_ReloadSceneNoSave.mel\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Open Scene..." 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OpenScene" 
                -keyEquivalent "O" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 1
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconFile.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

        setParent -m ..;

        menuItem
            -label "Playblasting" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

            menuItem
                -label "Playblast" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source GUI_Playblast;postvisPlayblast;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "PlayblastButton.bmp" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "toggle HUD" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "hud = hcam.Tools.HUD()\nhud.toggle(hcam.Ui.Cam.List.sls)" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Slate_HUD.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

        setParent -m ..;

        menuItem
            -label "Pivot" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

            menuItem
                -label "MovePivotToBase" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"C:/Users/aaikman/Documents/maya/2016/prefs/scripts/AA/AAMovePivotToBase.mel\";\n" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "menuEditorMenuItem2" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Move to Abs Origin" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "$obj=`ls -sl`;\nmove -rpr 0 0 0 $obj;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Set Pivot To Origin" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "xform -ws -a -rp 0 0 0" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "menuEditorMenuItem5" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

        setParent -m ..;

    setParent -m ..;

    menuItem
        -label "Export" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "E" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem3;

        menuItem
            -label "ExportSel" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ExportSelection;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "E" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "Import" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "Import;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "make Unreal-ready fbx" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "//this script should be run from an asset scene file.  \n\n//creates an fbx file of your asset ready for importing into Unreal engine\n\n\n    source \"hunreal/ASSET_createEngineReadyFBXFromAsset.mel\";\n" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "hunreal/icon32_assetFBX.bmp" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

        menuItem
            -label "MayaToUnreal_Sims" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "//THIS SCRIPT IS NOT UNDOABLE!  Save scene before exporting scene components to fbx.\n\n//Recommend baking all simulations before executing this script:\n\n//creates a joint for every simulation object\n//skins sim objects to respective joints\n//bakes animation\n//opens export dialogue box\n\n\nsource \"hunreal/MayaToUnreal_Sims.mel\";\n" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "S" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "hunreal/MayaToUnreal_Sim.bmp" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem13;

        menuItem
            -label "GoZ" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"C:/Users/Public/Pixologic/GoZApps/Maya/GoZBrushFromMaya.mel\"\n" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "C:/Users/aaikman/Documents/maya/2016/prefs/icons/GoZBrush.xpm" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "MayaToUnreal_Camera" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/MayaToUnreal_Camera.mel\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/MayaToUnreal_Camera.bmp" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "MayaToUnreal_hRig" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/MayaToUnreal_hRig.mel\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/MayaToUnreal_hRig.bmp" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "PRP No Constr" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/MayaToUnreal_Prop_NoConstraints.mel\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "commandButton.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

    setParent -m ..;

    menuItem
        -label "Object" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "S" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem4;

        menuItem
            -label "Cleanup" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CleanupPolygonOptions;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "Snapping" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

            menuItem
                -label "Snap Together" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "setToolTo snapTogetherToolCtx;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "AhSnap" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"UTIL_snapObject.mel\" ;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/AP3S/assets/SCRIPTS/icons/Snap.bmp" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "AhSwap" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "import swapObjects\nreload(swapObjects)\nswapObjects.display()" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/AP3S/assets/SCRIPTS/icons/Swap.bmp" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Snap Together Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "setToolTo snapTogetherToolCtx" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "snapTogetherTool.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Align Objects" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "performAlignObjects 0" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "alignObjects.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Position Along Curve" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PositionAlongCurve" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "positionAlongCurve.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "Point to Point" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SnapPointToPoint" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "pointToPoint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

        setParent -m ..;

        menuItem
            -label "Transform Components" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyMove \"\" 0" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "S" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyMoveVertex.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "menuEditorMenuItem8" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "MovePolygonComponentOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "Deformers" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

            menuItem
                -label "Bend" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Bend;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Lattice 5x5x5" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "lattice  -divisions 5 5 5 -objectCentered true;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Lattice 5x5x15" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "lattice  -divisions 5 5 15 -objectCentered true;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

        setParent -m ..;

        menuItem
            -label "Faces" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

            menuItem
                -label "AutoQuad" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Triangulate; Quadrangulate;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Fill Hole and AutoQuad" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "FillHole; Triangulate; Quadrangulate;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "FillHole" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "FillHole;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Bridge" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "performPolyBridgeEdge 0" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "polyBridge.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "menuEditorMenuItem5" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "BridgeEdgeOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Duplicate" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "performPolyChipOff 0 1" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "polyDuplicateFacet.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "menuEditorMenuItem7" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "DuplicateFaceOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "Extract" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "performPolyChipOff 0 0" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "polyChipOff.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem8;

            menuItem
                -label "menuEditorMenuItem9" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ExtractFaceOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

        setParent -m ..;

        menuItem
            -label "Combine Options" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

            menuItem
                -label "Combine" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "CombinePolygons" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "polyUnite.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Separate" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SeparatePolygon" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "polySeparate.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Combine n Merge" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "polyUnite; polyMergeVertex  -d 0.1;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

        setParent -m ..;

        menuItem
            -label "AutoQuad" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "Triangulate; Quadrangulate;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Materials" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "E" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

            menuItem
                -label "Assign New Lambert" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "createAndAssignShader lambert \"\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Assign Lambert 1" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "hyperShade -assign lambert1;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

        setParent -m ..;

    setParent -m ..;

    menuItem
        -label "Components" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SW" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem5;

        menuItem
            -label "Split Polygon" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SplitPolygonTool;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "TransformComp" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "MovePolygonComponent;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "SlideEdge" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SlideEdgeTool;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Split Edge" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

            menuItem
                -label "Split Half" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SplitEdgeRingTool;\npolySelectEditCtx -e -div 1 polySelectEditContext;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Split Fourths" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SplitEdgeRingTool;\npolySelectEditCtx -e -div 3 polySelectEditContext;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Split Equidistant" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SplitEdgeRingTool;\npolySelectEditCtx -e -splitType 0 polySelectEditContext; intSliderGrp -e -enable 0 selectEditSplitDivisionsSlider; checkBoxGrp -e -enable 0 selectEditUseEqualMultiplierCheckBox;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Split Relative" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SplitEdgeRingTool;\npolySelectEditCtx -e -splitType 1 polySelectEditContext; intSliderGrp -e -enable 0 selectEditSplitDivisionsSlider; checkBoxGrp -e -enable 0 selectEditUseEqualMultiplierCheckBox;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Split Normal" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SplitEdgeRingTool;\n" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Split Thirds" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SplitEdgeRingTool;\npolySelectEditCtx -e -div 2 polySelectEditContext;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

        setParent -m ..;

        menuItem
            -label "Sculpting" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

            menuItem
                -label "Smooth Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshSmoothTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Smooth.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "menuEditorMenuItem2" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshSmoothToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Sculpt Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshSculptTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Sculpt.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "menuEditorMenuItem4" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshSculptToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Grab Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshGrabTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Grab.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "menuEditorMenuItem6" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshGrabToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "Bulge Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshBulgeTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Bulge.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "menuEditorMenuItem8" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshBulgeToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem8;

            menuItem
                -label "Pinch Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshPinchTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Pinch.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

            menuItem
                -label "menuEditorMenuItem10" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshPinchToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem10;

            menuItem
                -label "Fill Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshFillTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Fill.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem11;

            menuItem
                -label "menuEditorMenuItem12" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshFillToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem12;

            menuItem
                -label "Flatten Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshFlattenTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Flatten.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem13;

            menuItem
                -label "menuEditorMenuItem14" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshFlattenToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem14;

            menuItem
                -label "Knife Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetMeshKnifeTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Knife.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem15;

            menuItem
                -label "menuEditorMenuItem16" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ShowMeshKnifeToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem16;

        setParent -m ..;

    setParent -m ..;

    menuItem
        -label "Display" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NE" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem1;

        menuItem
            -label "Isolate" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ToggleIsolateSelect;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "ToggleWireframeView" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"C:/Users/aaikman/Documents/maya/2016/prefs/scripts/AA/ToggleWosView.mel\"; ToggleWosView();" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Show All UI Elements" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ShowUIElements" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "menuIconDisplay.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "ToggleXrayObject" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"C:/Users/aaikman/Documents/maya/2016/prefs/scripts/AA/ToggleXrayObj.mel\"; ToggleXrayObj();" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "E" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "commandButton.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "menuEditorMenuItem6" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "ToggleXrayView" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"C:/Users/aaikman/Documents/maya/2016/prefs/scripts/AA/ToggleXrayView.mel\"; ToggleXrayView();" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "commandButton.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "menuEditorMenuItem8" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "AnmLayout" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "setNamedPanelLayout \"AAikman_LO\"; updateToolbox();" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "S" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "PerspOutlinerLayout" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "setNamedPanelLayout \"Persp/Outliner\"; updateToolbox();" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "ClippingPlanes" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

            menuItem
                -label "Far Clip to 9,000,000" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "string $cameras[] = `ls -cameras`;\r\n\r\nfor ($thisCamera in $cameras) {\r\n    setAttr ($thisCamera + \".bestFitClippingPlanes\") false;\r\n    setAttr ($thisCamera + \".farClipPlane\") 900000000;\r\n    }" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "ClippingPlanes_08.xpm" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Near Clip to .01" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "string $cameras[] = `ls -cameras`;\n\nfor ($thisCamera in $cameras) {\n    setAttr ($thisCamera + \".bestFitClippingPlanes\") false;\n    setAttr ($thisCamera + \".nearClipPlane\") .01;\n    }" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "ClippingPlanes_01.xpm" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Far Clip to 9,000" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "string $cameras[] = `ls -cameras`;\r\n\r\nfor ($thisCamera in $cameras) {\r\n    setAttr ($thisCamera + \".bestFitClippingPlanes\") false;\r\n    setAttr ($thisCamera + \".farClipPlane\") 9000;\r\n    }" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "ClippingPlanes_05.xpm" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Near Clip to 100" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "string $cameras[] = `ls -cameras`;\r\n\r\nfor ($thisCamera in $cameras) {\r\n    setAttr ($thisCamera + \".bestFitClippingPlanes\") false;\r\n    setAttr ($thisCamera + \".nearClipPlane\") 100;\r\n    }" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "ClippingPlanes_04.xpm" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Near Clip to .1" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "string $cameras[] = `ls -cameras`;\r\n\r\nfor ($thisCamera in $cameras) {\r\n    setAttr ($thisCamera + \".bestFitClippingPlanes\") false;\r\n    setAttr ($thisCamera + \".nearClipPlane\") .1;\r\n    }" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "ClippingPlanes_01.xpm" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

        setParent -m ..;

    setParent -m ..;

    menuItem
        -label "Normals" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SE" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem6;

        menuItem
            -label "Set Angle" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "polySoftEdge;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Unlock Normals" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "polyNormalPerVertex -ufn true" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "E" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormalUnlock.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Soften Edge" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SoftPolyEdgeElements 1" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polySoftEdge.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "Harden Edge" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SoftPolyEdgeElements 0" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "S" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyHardEdge.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "Reverse" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ReversePolygonNormals" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormal.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "menuEditorMenuItem9" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ReversePolygonNormalsOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "Conform" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ConformPolygonNormals" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormalsConform.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "Average" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "polyAverageNormal -prenormalize 1 -allowZeroNormal 0 -postnormalize 0 -distance 0.1 -replaceNormalXYZ 1 0 0 " 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormalAverage.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

        menuItem
            -label "menuEditorMenuItem12" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "AveragePolygonNormalsOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

        menuItem
            -label "Lock Normals" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "polyNormalPerVertex -fn true" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormalLock.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem13;

    setParent -m ..;

    menuItem
        -label "Instances" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "W" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem7;

        menuItem
            -label "Instance X" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "instance; scale -r -1 1 1;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "Instance Z" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "instance; scale -r 1 1 -1;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "E" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Instance Y" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "instance; scale -r 1 -1 1;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "MirrorsEdge" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "source \"C:/Users/aaikman/Documents/maya/2016/prefs/scripts/AA/MirrorsEdge.mel\"; MirrorsEdge();" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "S" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "commandButton.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "menuEditorMenuItem6" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

    setParent -m ..;

    menuItem
        -label "Misc" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NW" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem8;

        menuItem
            -label "Rigging" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "E" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

            menuItem
                -label "Bind Skin" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SmoothBindSkin" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "smoothSkin.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "menuEditorMenuItem2" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SmoothBindSkinOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Paint Skin Weights" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ArtPaintSkinWeightsTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "paintSkinWeights.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "menuEditorMenuItem4" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ArtPaintSkinWeightsToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Blend Shapes" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "CreateBlendShape" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "blendShape.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "menuEditorMenuItem6" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "CreateBlendShapeOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "Parent Constraint" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ParentConstraint" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "parentConstraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "menuEditorMenuItem8" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ParentConstraintOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem8;

            menuItem
                -label "Point Constraint" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PointConstraint" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posConstraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

            menuItem
                -label "menuEditorMenuItem10" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PointConstraintOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem10;

            menuItem
                -label "Orient Constraint" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OrientConstraint" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "orientConstraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem11;

            menuItem
                -label "menuEditorMenuItem12" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OrientConstraintOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem12;

            menuItem
                -label "Aim Constraint" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "AimConstraint" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "aimConstraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem13;

            menuItem
                -label "menuEditorMenuItem14" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "AimConstraintOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem14;

            menuItem
                -label "Pole Vector Constraint" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PoleVectorConstraint" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "poleVectorConstraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem15;

            menuItem
                -label "menuEditorMenuItem16" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PoleVectorConstraintOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem16;

        setParent -m ..;

        menuItem
            -label "Selection" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

            menuItem
                -label "SelAll" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "import hAutoRig\nreload(hAutoRig)\nan = hAutoRig.hAnim()\nan.controls_select(an.all)" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "hAnim_metal_b01.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "SelRoot" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "import hAutoRig\nreload(hAutoRig)\nan = hAutoRig.hAnim()\nan.controls_select(an.root)" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "hAnim_metal_b02.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Filter Selection for Root" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/UTIL_FilterSelectionToRoot.mel\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "menuEditorMenuItem4" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Alternate Selection Window" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/UTIL_AlternateSelect.mel\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Select Roots" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/UTIL_SelectRoots.mel\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/selectRoots.bmp" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "Hierarchy" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SelectHierarchy" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconSelect.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

        setParent -m ..;

        menuItem
            -label "Curves" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

            menuItem
                -label "Rebuild" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "performRebuildCurveSet 1 1 0 0.01 4 3 1 0 0 1 0 1 0.05" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "rebuildCurve.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "EP Curve Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "EPCurveTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "curveEP.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "menuEditorMenuItem3" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "EPCurveToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "CV Curve" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "CVCurveTool;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

        setParent -m ..;

        menuItem
            -label "Skinning and SDK" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "S" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

            menuItem
                -label "Set..." 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SetDrivenKeyOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconKeys.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Paint Vertex Color Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PaintVertexColorTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "paintVertexColour.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "menuEditorMenuItem3" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PaintVertexColorToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Mirror Skin Weights" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "MirrorSkinWeights" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "mirrorSkinWeight.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Copy Skin Weights" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "CopySkinWeights" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "copySkinWeight.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Copy Vertex Weights" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "artAttrSkinWeightCopy" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconSkinning.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "Paste Vertex Weights" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "artAttrSkinWeightPaste" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconSkinning.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "Mirror Joints" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "mirrorJoint -mirrorYZ -mirrorBehavior -searchReplace \"_L\" \"_R\"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "kinMirrorJoint_S.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem8;

            menuItem
                -label "Create Joints" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "JointTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "kinJoint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

            menuItem
                -label "Paint Skin Weights" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ArtPaintSkinWeightsTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "paintSkinWeights.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 0
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem10;

            menuItem
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "ArtPaintSkinWeightsToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 0
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem11;

        setParent -m ..;

        menuItem
            -label "UVS" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

            menuItem
                -label "Create UVs Based On Cam" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "polyProjection -type Planar -md p" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Merge UVs" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "polyPerformAction \"polyMergeUV -d 0.01\" v 0;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "menuEditorMenuItem3" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "UVOffset" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"C:/Users/aaikman/Documents/maya/2016/prefs/scripts/AA/UVOffset.mel\"; UVOffset();" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "menuEditorMenuItem5" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

        setParent -m ..;

        menuItem
            -label "Animation" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

            menuItem
                -label "Bake Hierarchy" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "float $startTime = `playbackOptions -q -min`;\nfloat $endTime=`playbackOptions -q -max`;\nbakeResults -simulation true -t ($startTime+\":\"+$endTime) -hierarchy below -sampleBy 1 -disableImplicitControl true -preserveOutsideKeys false -sparseAnimCurveBake false -removeBakedAttributeFromLayer false -removeBakedAnimFromLayer false -bakeOnOverrideLayer false -minimizeRotation true -controlPoints false -shape true ;\nperformEulerFilter graphEditor1FromOutliner;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/Bake.bmp" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "oaSmoothKeys" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "oaSmoothKeys" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "commandButton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Send Prop to Mobu" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/MayaToMobu_Prop.mel\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/MayaPropMobu.bmp" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Import prop from Mobu" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/ANIM_fbxToMayaProp.mel\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/MobuPropMaya.bmp" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Change Namespace of Non-referenced Object" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/UTIL_ChangeNamespace.mel\";" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "SE" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/ChangeNamespace.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Select Hierarchy And Move Keys" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SelectHierarchy;\nstring $prompt =`promptDialog -t \"move selected Keys over time\" -m \"enter an integer value\" -b \"move Key\" -b \"cancel\" -db \"move Key\" -cb \"cancel\"`;\nif($prompt==\"move Key\")\n{\n\tstring $moveKey =`promptDialog -q tx`;\n\tprint $moveKey;\n\tfloat $tcFloat=$moveKey\t;\n\tkeyframe -r -tc $tcFloat;\n}\n" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "hAnim_metal_b41.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "move key" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "string $prompt =`promptDialog -t \"move selected Keys over time\" -m \"enter an integer value\" -b \"move Key\" -b \"cancel\" -db \"move Key\" -cb \"cancel\"`;\nif($prompt==\"move Key\")\n{\n\tstring $moveKey =`promptDialog -q tx`;\n\tprint $moveKey;\n\tfloat $tcFloat=$moveKey\t;\n\tkeyframe -r -tc $tcFloat;\n}\n" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "hAnim_metal_b41.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

        setParent -m ..;

        menuItem
            -label "Creation" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

            menuItem
                -label "Create subject locator" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "mt = hcam.Tools.Measure()\nmt.subject_loc(hcam.Ui.Cam.List.sls)" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "S" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Slate_subject.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Create Locator" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"//halonblade/hblade/InProd/Orville/assets/SCRIPTS/mel/UTIL_locatorAtSelection.mel\" ;\n" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "W" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "locator.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Import prod hCam" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "default = hcam.Tools.Default()\ncam = default.cam_import()" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "Slate_Import.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "wiz_controllers" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "wiz_controllers ()\n" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "E" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/Orville/assets/SCRIPTS/icons/wiz_icons/b01.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Magner's Referencer" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "source \"GUI_ImportRefMultipleObjects_AP3S.mel\" ;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "NW" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "//halonblade/hblade/InProd/AP3S/assets/SCRIPTS/icons/ReferenceSign.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

        setParent -m ..;

    setParent -m ..;

setParent -m ..;

